---
- name: System preparation | Set hostname 
  ansible.builtin.hostname:
    name: 'hostname'

- name: System preparation | Install chrony and wget]
  dnf: 
    name: 
      - chrony
      - wget
    state: latest

- name: System preparation | Set timezone
  community.general.timezone:
    name: '{{ timezone }}'
  notify:
    - Started and Enabled chronyd

- name: Security Settings | Configure rule firewealld
  firewalld: 
    port: '{{ item }}'
    permanent: yes 
    state: enabled 
  loop: 
    - 995/tcp
    - 993/tcp
    - 587/tcp
    - 465/tcp
    - 443/tcp
    - 143/tcp
    - 110/tcp
    - 80/tcp
    - 25/tcp
  notify: 
    - Restarted Firewalld

- name: Security Settings | Disable SELinux 
  ansible.posix.selinux:
    state: disabled

- name: Security Settings | Disable SELinux now
  command: 
    cmd: setenforce 0 
  when: 
    - ansible_selinux.status == "enabled"

- name: Configuring the Web Server | Install nginx
  dnf: 
    name: nginx 
    state: latest 
  
- name: Configuring the Web Server | Started and Enabled nginx 
  service: 
    name: nginx 
    enabled: true 
    state: started

- name: Configuring the Web Server | Install epel-release
  dnf: 
    name: epel-release
    state: latest 

- name: Configuring the Web Server | Install remi-reliase
  command:
    cmd: dnf install -y http://rpms.remirepo.net/enterprise/remi-release-8.rpm

- name: Configuring the Web Server | Installing PHP from the REMI repository
  dnf: 
    name: '@php:remi-7.2'
    state: present

- name: Configuring the Web Server | Install php-fpm
  dnf: 
    name: php-fpm
    state: latest

- name: Configuring the Web Server | Setting nginx.conf for working php
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - Started and Enabled php-fpm
    - Restarted nginx

- name: Configuring the Wev Server | Install MariaDB
  dnf:
    name: 
      - mariadb-server 
      - mariadb
      - python3-PyMySQL
    state: latest

- name: Configuring the Wev Server | Started and Enabled MariaDB 
  service: 
    name: mariadb 
    state: started 
    enabled: true

- name: Configuring the Wev Server | Configure root password MariaDB
  mysql_user:
    check_implicit_admin: true
    login_user: root 
    login_password: "{{ mariadb_root_password }}"
    user: root 
    password: "{{ mariadb_root_password }}"
    host: localhost

- name: Installing and configuring PostfixAdmin | Installing additional components for PHP
  dnf: 
    name: 
      - php-mysqli 
      - php-mbstring 
      - php-imap
    state: latest